### ISSUE TITLE
Remove "About this site" banner

### ISSUE THREAD

**Issue by snadi** [ualberta-se/ualberta-se.github.io#19]

**Comment by elahehmo** [comment]
I removed picture from the banner and wrote group description on top of that.Is it OK?
Because I thought may be by removing the banner, the whole page become white and it doesn't make sense.

**Comment by snadi** [comment]
@elahehmo  Can you create a picture with "SERL" written in it (e.g., by creating a powerpoint slide and exporting it as a picture for now) and use that inside the banner. Then, move the group description text below the banner?
